CREATE TABLE student (
id BIGINT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
birthday DATE NOT NULL,
grade INT NOT NULL);

CREATE TABLE subject (
id BIGINT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
description VARCHAR(100) NOT NULL,
grade INT NOT NULL);

CREATE TABLE payment_type(
id BIGINT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL);

CREATE TABLE Payment (
id BIGINT NOT NULL PRIMARY KEY,
type_id BIGINT REFERENCES paymentType(id) NOT NULL,
amount DECIMAL(10, 2) NOT NULL,
student_id BIGINT REFERENCES student(id) NOT NULL,
payment_date TIMESTAMP);

CREATE TABLE mark (
id BIGINT NOT NULL PRIMARY KEY,
student_id BIGINT REFERENCES student(id) NOT NULL,
subject_id BIGINT REFERENCES subject(id) NOT NULL,
mark INT NOT NULL
);
